# Change these first
owner: cog-creators # Your GitHub username
repo: red-status # Your Github repository name

# Add your sites here
sites:
  - name: Cog board
    url: https://cogboard.discord.red
  - name: Index (web interface)
    url: https://index.discord.red
  - name: Red-GitHubBot
    url: https://red-githubbot.fly.dev
    assignees:
      - Jackenmen

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.discord.red
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Red Status
  introTitle: "Keep track of Red services across the board here."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
